name: CI-CD

on:
  pull_request:
    branches: [ "master" ]
    types:
      - edited
      - labeled
      - opened
      - reopened
      - synchronize
  push:
    branches: [ "master" ]
    paths:
      - '../labels.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sync-labels:
    name: Sync Repository Labels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: micnncim/action-label-syncer@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  labeler:
    name: Pull Request Labels
    needs: [sync-labels]
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      # Label Based on Modified Files
      - name: Label Based on Modified Files
        uses: actions/labeler@v6
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      # Label Based on Branch Name
      - uses: actions-ecosystem/action-add-labels@v1
        if: startsWith(github.event.pull_request.head.ref, 'fix')
        with:
          labels: bug

      - uses: actions-ecosystem/action-add-labels@v1
        if: |
          startsWith(github.event.pull_request.head.ref, 'doc') ||
          startsWith(github.event.pull_request.head.ref, 'docs')
        with:
          labels: documentation

      - uses: actions-ecosystem/action-add-labels@v1
        if: startsWith(github.event.pull_request.head.ref, 'feat')
        with:
          labels: enhancement

      - uses: actions-ecosystem/action-add-labels@v1
        if: |
          startsWith(github.event.pull_request.head.ref, 'ci') ||
          startsWith(github.event.pull_request.head.ref, 'maint')
        with:
          labels: maintenace


  commenter:
    name: Labels Comment
    runs-on: ubuntu-latest

    steps:
    - name: Suggest Labels
      uses: peter-evans/create-or-update-comment@v5

      # Execute only when no labels have been applied to the pull request
      if: toJSON(github.event.pull_request.labels.*.name) == '{}'
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          Please add one of the following labels:
          - [bug](https://github.com/tr0fin0/latex-cv/pulls?q=label%3Abug+)
          - [documentation](https://github.com/tr0fin0/latex-cv/pulls?q=label%3Adocumentation+)
          - [enhancement](https://github.com/tr0fin0/latex-cv/pulls?q=label%3Aenhancement+)
          - [maintenance](https://github.com/tr0fin0/latex-cv/pulls?q=label%3Amaintenance+)


  pull-request-title:
    name: Pull Request Name
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read

    steps:
      - uses: actions/checkout@v6

      - uses: amannn/action-semantic-pull-request@v6
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}