name: LaTeX Build

on: [push]

jobs:
  LaTeX:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v4
        with:
          root_file: cv.tex

      - name: Upload PDF
        uses: actions/upload-artifact@v5
        with:
          name: PDF
          path: cv.pdf