name: LaTeX Build


on:
  pull_request:
    branches: [ "master" ]
    paths:
      - '**.tex'


jobs:
  LaTeX:
    name: Compile LaTeX File
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@25080975331dc4fc8e6f1af55788e00f84f51fff #v4.0.0
        with:
          root_file: cv.tex

      - name: Upload PDF
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f #v6.0.0
        with:
          name: PDF
          path: cv.pdf