name: LaTeX Build


on:
  push:
    paths:
      - '**.tex'
  pull_request:
    branches: [ "master" ]
    paths:
      - '**.tex'


jobs:
  LaTeX:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v4
        with:
          root_file: cv.tex

      - name: Upload PDF
        uses: actions/upload-artifact@v6
        with:
          name: PDF
          path: cv.pdf